export default {
    'latitude': 28.6708964,
    'longitude': 77.1532642,
    'timezone': 'Asia/Kolkata',
    'currently': {
        'time': 1552783302,
        'summary': 'Foggy',
        'icon': 'fog',
        'precipIntensity': 0,
        'precipProbability': 0,
        'temperature': 15.75,
        'apparentTemperature': 15.75,
        'dewPoint': 12.11,
        'humidity': 0.79,
        'pressure': 1014.37,
        'windSpeed': 1.97,
        'windGust': 2.46,
        'windBearing': 255,
        'cloudCover': 0.4,
        'uvIndex': 0,
        'visibility': 1.72,
        'ozone': 272.52
    },
    'hourly': {
        'summary': 'Foggy later this morning.',
        'icon': 'fog',
        'data': [{
                'time': 1552782600,
                'summary': 'Foggy',
                'icon': 'fog',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 15.63,
                'apparentTemperature': 15.63,
                'dewPoint': 12.13,
                'humidity': 0.8,
                'pressure': 1014.26,
                'windSpeed': 1.99,
                'windGust': 2.38,
                'windBearing': 255,
                'cloudCover': 0.41,
                'uvIndex': 0,
                'visibility': 1.5,
                'ozone': 272.39
            },
            {
                'time': 1552786200,
                'summary': 'Foggy',
                'icon': 'fog',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 16.25,
                'apparentTemperature': 16.25,
                'dewPoint': 11.97,
                'humidity': 0.76,
                'pressure': 1014.82,
                'windSpeed': 1.9,
                'windGust': 2.79,
                'windBearing': 258,
                'cloudCover': 0.37,
                'uvIndex': 0,
                'visibility': 2.67,
                'ozone': 273.04
            },
            {
                'time': 1552789800,
                'summary': 'Partly Cloudy',
                'icon': 'partly-cloudy-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 17.43,
                'apparentTemperature': 17.43,
                'dewPoint': 10.28,
                'humidity': 0.63,
                'pressure': 1015.37,
                'windSpeed': 1.8,
                'windGust': 3.21,
                'windBearing': 277,
                'cloudCover': 0.47,
                'uvIndex': 1,
                'visibility': 9.99,
                'ozone': 273.64
            },
            {
                'time': 1552793400,
                'summary': 'Mostly Cloudy',
                'icon': 'partly-cloudy-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 19.39,
                'apparentTemperature': 19.39,
                'dewPoint': 7.93,
                'humidity': 0.47,
                'pressure': 1015.66,
                'windSpeed': 2.09,
                'windGust': 3.25,
                'windBearing': 301,
                'cloudCover': 0.65,
                'uvIndex': 2,
                'visibility': 16.09,
                'ozone': 274.25
            },
            {
                'time': 1552797000,
                'summary': 'Mostly Cloudy',
                'icon': 'partly-cloudy-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 21.78,
                'apparentTemperature': 21.78,
                'dewPoint': 7.18,
                'humidity': 0.39,
                'pressure': 1015.68,
                'windSpeed': 2.42,
                'windGust': 2.91,
                'windBearing': 310,
                'cloudCover': 0.73,
                'uvIndex': 4,
                'visibility': 16.09,
                'ozone': 274.89
            },
            {
                'time': 1552800600,
                'summary': 'Mostly Cloudy',
                'icon': 'partly-cloudy-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 24.01,
                'apparentTemperature': 24.01,
                'dewPoint': 7.24,
                'humidity': 0.34,
                'pressure': 1015.49,
                'windSpeed': 2.55,
                'windGust': 2.63,
                'windBearing': 313,
                'cloudCover': 0.69,
                'uvIndex': 5,
                'visibility': 16.09,
                'ozone': 275.53
            },
            {
                'time': 1552804200,
                'summary': 'Partly Cloudy',
                'icon': 'partly-cloudy-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 25.61,
                'apparentTemperature': 25.61,
                'dewPoint': 6.77,
                'humidity': 0.3,
                'pressure': 1014.97,
                'windSpeed': 2.53,
                'windGust': 2.53,
                'windBearing': 312,
                'cloudCover': 0.55,
                'uvIndex': 7,
                'visibility': 16.09,
                'ozone': 276.21
            },
            {
                'time': 1552807800,
                'summary': 'Partly Cloudy',
                'icon': 'partly-cloudy-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 26.69,
                'apparentTemperature': 26.69,
                'dewPoint': 5.79,
                'humidity': 0.26,
                'pressure': 1014.14,
                'windSpeed': 2.38,
                'windGust': 2.4,
                'windBearing': 308,
                'cloudCover': 0.32,
                'uvIndex': 8,
                'visibility': 16.09,
                'ozone': 276.92
            },
            {
                'time': 1552811400,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 27.48,
                'apparentTemperature': 27.48,
                'dewPoint': 4.84,
                'humidity': 0.24,
                'pressure': 1013.27,
                'windSpeed': 2.24,
                'windGust': 2.31,
                'windBearing': 304,
                'cloudCover': 0.09,
                'uvIndex': 7,
                'visibility': 16.09,
                'ozone': 277.49
            },
            {
                'time': 1552815000,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 27.95,
                'apparentTemperature': 27.95,
                'dewPoint': 4.43,
                'humidity': 0.22,
                'pressure': 1012.65,
                'windSpeed': 2.22,
                'windGust': 2.45,
                'windBearing': 304,
                'cloudCover': 0,
                'uvIndex': 5,
                'visibility': 16.09,
                'ozone': 277.59
            },
            {
                'time': 1552818600,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 28.09,
                'apparentTemperature': 28.09,
                'dewPoint': 4.52,
                'humidity': 0.22,
                'pressure': 1012.26,
                'windSpeed': 2.31,
                'windGust': 2.83,
                'windBearing': 308,
                'cloudCover': 0,
                'uvIndex': 3,
                'visibility': 16.09,
                'ozone': 277.26
            },
            {
                'time': 1552822200,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 27.79,
                'apparentTemperature': 27.79,
                'dewPoint': 4.8,
                'humidity': 0.23,
                'pressure': 1012.09,
                'windSpeed': 2.37,
                'windGust': 3.18,
                'windBearing': 315,
                'cloudCover': 0,
                'uvIndex': 1,
                'visibility': 16.09,
                'ozone': 276.81
            },
            {
                'time': 1552825800,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 26.66,
                'apparentTemperature': 26.66,
                'dewPoint': 5.17,
                'humidity': 0.25,
                'pressure': 1012.25,
                'windSpeed': 2.27,
                'windGust': 3.21,
                'windBearing': 326,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 276.53
            },
            {
                'time': 1552829400,
                'summary': 'Clear',
                'icon': 'clear-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 24.75,
                'apparentTemperature': 24.75,
                'dewPoint': 5.66,
                'humidity': 0.29,
                'pressure': 1012.72,
                'windSpeed': 2.03,
                'windGust': 2.91,
                'windBearing': 343,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 276.52
            },
            {
                'time': 1552833000,
                'summary': 'Clear',
                'icon': 'clear-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 22.67,
                'apparentTemperature': 22.67,
                'dewPoint': 6.14,
                'humidity': 0.34,
                'pressure': 1013.27,
                'windSpeed': 1.81,
                'windGust': 2.53,
                'windBearing': 358,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 276.56
            },
            {
                'time': 1552836600,
                'summary': 'Clear',
                'icon': 'clear-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 21.05,
                'apparentTemperature': 21.05,
                'dewPoint': 6.48,
                'humidity': 0.39,
                'pressure': 1013.67,
                'windSpeed': 1.64,
                'windGust': 2.3,
                'windBearing': 0,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 276.57
            },
            {
                'time': 1552840200,
                'summary': 'Clear',
                'icon': 'clear-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 20.01,
                'apparentTemperature': 20.01,
                'dewPoint': 6.64,
                'humidity': 0.42,
                'pressure': 1013.91,
                'windSpeed': 1.53,
                'windGust': 2.2,
                'windBearing': 349,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 276.56
            },
            {
                'time': 1552843800,
                'summary': 'Clear',
                'icon': 'clear-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 19.2,
                'apparentTemperature': 19.2,
                'dewPoint': 6.72,
                'humidity': 0.44,
                'pressure': 1014.01,
                'windSpeed': 1.48,
                'windGust': 2.16,
                'windBearing': 335,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 276.38
            },
            {
                'time': 1552847400,
                'summary': 'Clear',
                'icon': 'clear-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 18.47,
                'apparentTemperature': 18.47,
                'dewPoint': 6.67,
                'humidity': 0.46,
                'pressure': 1013.89,
                'windSpeed': 1.49,
                'windGust': 2.15,
                'windBearing': 326,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 275.95
            },
            {
                'time': 1552851000,
                'summary': 'Clear',
                'icon': 'clear-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 17.79,
                'apparentTemperature': 17.79,
                'dewPoint': 6.51,
                'humidity': 0.48,
                'pressure': 1013.55,
                'windSpeed': 1.55,
                'windGust': 2.18,
                'windBearing': 322,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 275.31
            },
            {
                'time': 1552854600,
                'summary': 'Clear',
                'icon': 'clear-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 17.13,
                'apparentTemperature': 17.13,
                'dewPoint': 6.36,
                'humidity': 0.49,
                'pressure': 1013.19,
                'windSpeed': 1.63,
                'windGust': 2.26,
                'windBearing': 320,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 274.56
            },
            {
                'time': 1552858200,
                'summary': 'Clear',
                'icon': 'clear-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 16.32,
                'apparentTemperature': 16.32,
                'dewPoint': 6.33,
                'humidity': 0.52,
                'pressure': 1012.97,
                'windSpeed': 1.7,
                'windGust': 2.47,
                'windBearing': 316,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 273.75
            },
            {
                'time': 1552861800,
                'summary': 'Clear',
                'icon': 'clear-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 15.43,
                'apparentTemperature': 15.43,
                'dewPoint': 6.44,
                'humidity': 0.55,
                'pressure': 1012.88,
                'windSpeed': 1.77,
                'windGust': 2.8,
                'windBearing': 311,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 272.97
            },
            {
                'time': 1552865400,
                'summary': 'Clear',
                'icon': 'clear-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 15.02,
                'apparentTemperature': 15.02,
                'dewPoint': 6.63,
                'humidity': 0.57,
                'pressure': 1012.93,
                'windSpeed': 1.81,
                'windGust': 3.08,
                'windBearing': 312,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 272.22
            },
            {
                'time': 1552869000,
                'summary': 'Clear',
                'icon': 'clear-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 15.59,
                'apparentTemperature': 15.59,
                'dewPoint': 6.96,
                'humidity': 0.56,
                'pressure': 1013.26,
                'windSpeed': 1.65,
                'windGust': 3.07,
                'windBearing': 331,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 271.58
            },
            {
                'time': 1552872600,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 17.02,
                'apparentTemperature': 17.02,
                'dewPoint': 7.41,
                'humidity': 0.53,
                'pressure': 1013.83,
                'windSpeed': 1.49,
                'windGust': 2.77,
                'windBearing': 328,
                'cloudCover': 0,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 271.08
            },
            {
                'time': 1552876200,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 18.82,
                'apparentTemperature': 18.82,
                'dewPoint': 7.87,
                'humidity': 0.49,
                'pressure': 1014.39,
                'windSpeed': 1.56,
                'windGust': 2.42,
                'windBearing': 307,
                'cloudCover': 0,
                'uvIndex': 1,
                'visibility': 16.09,
                'ozone': 270.69
            },
            {
                'time': 1552879800,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 21.01,
                'apparentTemperature': 21.01,
                'dewPoint': 8.21,
                'humidity': 0.44,
                'pressure': 1014.71,
                'windSpeed': 1.55,
                'windGust': 2.22,
                'windBearing': 304,
                'cloudCover': 0,
                'uvIndex': 3,
                'visibility': 16.09,
                'ozone': 270.38
            },
            {
                'time': 1552883400,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 23.55,
                'apparentTemperature': 23.55,
                'dewPoint': 8.39,
                'humidity': 0.38,
                'pressure': 1014.76,
                'windSpeed': 1.52,
                'windGust': 2.16,
                'windBearing': 320,
                'cloudCover': 0,
                'uvIndex': 6,
                'visibility': 16.09,
                'ozone': 270.18
            },
            {
                'time': 1552887000,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 25.87,
                'apparentTemperature': 25.87,
                'dewPoint': 8.31,
                'humidity': 0.33,
                'pressure': 1014.57,
                'windSpeed': 1.69,
                'windGust': 2.2,
                'windBearing': 322,
                'cloudCover': 0,
                'uvIndex': 8,
                'visibility': 16.09,
                'ozone': 269.9
            },
            {
                'time': 1552890600,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 27.46,
                'apparentTemperature': 27.46,
                'dewPoint': 7.88,
                'humidity': 0.29,
                'pressure': 1014.02,
                'windSpeed': 1.94,
                'windGust': 2.33,
                'windBearing': 303,
                'cloudCover': 0,
                'uvIndex': 10,
                'visibility': 16.09,
                'ozone': 269.33
            },
            {
                'time': 1552894200,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 28.5,
                'apparentTemperature': 28.5,
                'dewPoint': 7.12,
                'humidity': 0.26,
                'pressure': 1013.1,
                'windSpeed': 2.15,
                'windGust': 2.55,
                'windBearing': 301,
                'cloudCover': 0,
                'uvIndex': 10,
                'visibility': 16.09,
                'ozone': 268.48
            },
            {
                'time': 1552897800,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 29.29,
                'apparentTemperature': 29.29,
                'dewPoint': 6.34,
                'humidity': 0.24,
                'pressure': 1012.13,
                'windSpeed': 2.35,
                'windGust': 2.82,
                'windBearing': 303,
                'cloudCover': 0,
                'uvIndex': 8,
                'visibility': 16.09,
                'ozone': 267.64
            },
            {
                'time': 1552901400,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 29.77,
                'apparentTemperature': 29.77,
                'dewPoint': 5.89,
                'humidity': 0.22,
                'pressure': 1011.4,
                'windSpeed': 2.5,
                'windGust': 3.1,
                'windBearing': 307,
                'cloudCover': 0,
                'uvIndex': 6,
                'visibility': 16.09,
                'ozone': 267.01
            },
            {
                'time': 1552905000,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 29.93,
                'apparentTemperature': 29.93,
                'dewPoint': 5.75,
                'humidity': 0.22,
                'pressure': 1010.91,
                'windSpeed': 2.6,
                'windGust': 3.39,
                'windBearing': 311,
                'cloudCover': 0,
                'uvIndex': 3,
                'visibility': 16.09,
                'ozone': 266.53
            },
            {
                'time': 1552908600,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 29.69,
                'apparentTemperature': 29.69,
                'dewPoint': 5.8,
                'humidity': 0.22,
                'pressure': 1010.65,
                'windSpeed': 2.65,
                'windGust': 3.61,
                'windBearing': 318,
                'cloudCover': 0,
                'uvIndex': 1,
                'visibility': 16.09,
                'ozone': 266.31
            },
            {
                'time': 1552912200,
                'summary': 'Clear',
                'icon': 'clear-day',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 28.64,
                'apparentTemperature': 28.64,
                'dewPoint': 6.08,
                'humidity': 0.24,
                'pressure': 1010.78,
                'windSpeed': 2.62,
                'windGust': 3.66,
                'windBearing': 329,
                'cloudCover': 0.12,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 266.49
            },
            {
                'time': 1552915800,
                'summary': 'Partly Cloudy',
                'icon': 'partly-cloudy-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 26.77,
                'apparentTemperature': 26.77,
                'dewPoint': 6.63,
                'humidity': 0.28,
                'pressure': 1011.28,
                'windSpeed': 2.56,
                'windGust': 3.52,
                'windBearing': 344,
                'cloudCover': 0.41,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 267.14
            },
            {
                'time': 1552919400,
                'summary': 'Mostly Cloudy',
                'icon': 'partly-cloudy-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 24.68,
                'apparentTemperature': 24.68,
                'dewPoint': 7.23,
                'humidity': 0.33,
                'pressure': 1011.84,
                'windSpeed': 2.49,
                'windGust': 3.3,
                'windBearing': 356,
                'cloudCover': 0.69,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 268.04
            },
            {
                'time': 1552923000,
                'summary': 'Mostly Cloudy',
                'icon': 'partly-cloudy-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 23.04,
                'apparentTemperature': 23.04,
                'dewPoint': 7.67,
                'humidity': 0.37,
                'pressure': 1012.17,
                'windSpeed': 2.32,
                'windGust': 3.04,
                'windBearing': 358,
                'cloudCover': 0.86,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 268.98
            },
            {
                'time': 1552926600,
                'summary': 'Mostly Cloudy',
                'icon': 'partly-cloudy-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 22.01,
                'apparentTemperature': 22.01,
                'dewPoint': 7.93,
                'humidity': 0.4,
                'pressure': 1012.25,
                'windSpeed': 2.03,
                'windGust': 2.73,
                'windBearing': 350,
                'cloudCover': 0.91,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 269.95
            },
            {
                'time': 1552930200,
                'summary': 'Mostly Cloudy',
                'icon': 'partly-cloudy-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 21.18,
                'apparentTemperature': 21.18,
                'dewPoint': 8.09,
                'humidity': 0.43,
                'pressure': 1012.15,
                'windSpeed': 1.73,
                'windGust': 2.39,
                'windBearing': 338,
                'cloudCover': 0.9,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 270.91
            },
            {
                'time': 1552933800,
                'summary': 'Mostly Cloudy',
                'icon': 'partly-cloudy-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 20.45,
                'apparentTemperature': 20.45,
                'dewPoint': 8.14,
                'humidity': 0.45,
                'pressure': 1011.83,
                'windSpeed': 1.5,
                'windGust': 1.98,
                'windBearing': 329,
                'cloudCover': 0.84,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 271.69
            },
            {
                'time': 1552937400,
                'summary': 'Mostly Cloudy',
                'icon': 'partly-cloudy-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 19.76,
                'apparentTemperature': 19.76,
                'dewPoint': 8.09,
                'humidity': 0.47,
                'pressure': 1011.29,
                'windSpeed': 1.32,
                'windGust': 1.54,
                'windBearing': 324,
                'cloudCover': 0.74,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 272.33
            },
            {
                'time': 1552941000,
                'summary': 'Mostly Cloudy',
                'icon': 'partly-cloudy-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 19.1,
                'apparentTemperature': 19.1,
                'dewPoint': 8.01,
                'humidity': 0.49,
                'pressure': 1010.71,
                'windSpeed': 1.21,
                'windGust': 1.27,
                'windBearing': 320,
                'cloudCover': 0.63,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 273.02
            },
            {
                'time': 1552944600,
                'summary': 'Partly Cloudy',
                'icon': 'partly-cloudy-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 18.28,
                'apparentTemperature': 18.28,
                'dewPoint': 7.95,
                'humidity': 0.51,
                'pressure': 1010.27,
                'windSpeed': 1.22,
                'windGust': 1.31,
                'windBearing': 315,
                'cloudCover': 0.54,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 274.04
            },
            {
                'time': 1552948200,
                'summary': 'Partly Cloudy',
                'icon': 'partly-cloudy-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 17.37,
                'apparentTemperature': 17.37,
                'dewPoint': 7.93,
                'humidity': 0.54,
                'pressure': 1009.95,
                'windSpeed': 1.38,
                'windGust': 1.75,
                'windBearing': 310,
                'cloudCover': 0.49,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 275.37
            },
            {
                'time': 1552951800,
                'summary': 'Partly Cloudy',
                'icon': 'partly-cloudy-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 16.92,
                'apparentTemperature': 16.92,
                'dewPoint': 7.93,
                'humidity': 0.55,
                'pressure': 1009.81,
                'windSpeed': 1.59,
                'windGust': 2.42,
                'windBearing': 309,
                'cloudCover': 0.43,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 276.8
            },
            {
                'time': 1552955400,
                'summary': 'Partly Cloudy',
                'icon': 'partly-cloudy-night',
                'precipIntensity': 0,
                'precipProbability': 0,
                'temperature': 17.41,
                'apparentTemperature': 17.41,
                'dewPoint': 8.03,
                'humidity': 0.54,
                'pressure': 1010,
                'windSpeed': 1.69,
                'windGust': 2.94,
                'windBearing': 316,
                'cloudCover': 0.33,
                'uvIndex': 0,
                'visibility': 16.09,
                'ozone': 278.24
            }
        ]
    },
    'daily': {
        'summary': 'No precipitation throughout the week, with high temperatures rising to 33°C on Thursday.',
        'icon': 'clear-day',
        'data': [{
                'time': 1552761000,
                'summary': 'Foggy in the morning.',
                'icon': 'fog',
                'sunriseTime': 1552784430,
                'sunsetTime': 1552827708,
                'moonPhase': 0.36,
                'precipIntensity': 0,
                'precipIntensityMax': 0,
                'precipProbability': 0,
                'temperatureHigh': 28.09,
                'temperatureHighTime': 1552818600,
                'temperatureLow': 15.02,
                'temperatureLowTime': 1552865400,
                'apparentTemperatureHigh': 28.09,
                'apparentTemperatureHighTime': 1552818600,
                'apparentTemperatureLow': 15.02,
                'apparentTemperatureLowTime': 1552865400,
                'dewPoint': 7.73,
                'humidity': 0.45,
                'pressure': 1013.98,
                'windSpeed': 1.61,
                'windGust': 3.25,
                'windGustTime': 1552793400,
                'windBearing': 307,
                'cloudCover': 0.32,
                'uvIndex': 8,
                'uvIndexTime': 1552807800,
                'visibility': 12.34,
                'ozone': 274.5,
                'temperatureMin': 15.63,
                'temperatureMinTime': 1552782600,
                'temperatureMax': 28.09,
                'temperatureMaxTime': 1552818600,
                'apparentTemperatureMin': 15.63,
                'apparentTemperatureMinTime': 1552782600,
                'apparentTemperatureMax': 28.09,
                'apparentTemperatureMaxTime': 1552818600
            },
            {
                'time': 1552847400,
                'summary': 'Mostly cloudy starting in the evening.',
                'icon': 'partly-cloudy-night',
                'sunriseTime': 1552870760,
                'sunsetTime': 1552914142,
                'moonPhase': 0.4,
                'precipIntensity': 0.0025,
                'precipIntensityMax': 0.0051,
                'precipIntensityMaxTime': 1552879800,
                'precipProbability': 0.02,
                'precipType': 'rain',
                'temperatureHigh': 29.93,
                'temperatureHighTime': 1552905000,
                'temperatureLow': 16.92,
                'temperatureLowTime': 1552951800,
                'apparentTemperatureHigh': 29.93,
                'apparentTemperatureHighTime': 1552905000,
                'apparentTemperatureLow': 16.92,
                'apparentTemperatureLowTime': 1552951800,
                'dewPoint': 7.02,
                'humidity': 0.39,
                'pressure': 1012.82,
                'windSpeed': 1.88,
                'windGust': 3.66,
                'windGustTime': 1552912200,
                'windBearing': 323,
                'cloudCover': 0.16,
                'uvIndex': 10,
                'uvIndexTime': 1552890600,
                'visibility': 16.09,
                'ozone': 270.22,
                'temperatureMin': 15.02,
                'temperatureMinTime': 1552865400,
                'temperatureMax': 29.93,
                'temperatureMaxTime': 1552905000,
                'apparentTemperatureMin': 15.02,
                'apparentTemperatureMinTime': 1552865400,
                'apparentTemperatureMax': 29.93,
                'apparentTemperatureMaxTime': 1552905000
            },
            {
                'time': 1552933800,
                'summary': 'Partly cloudy in the morning.',
                'icon': 'partly-cloudy-night',
                'sunriseTime': 1552957090,
                'sunsetTime': 1553000575,
                'moonPhase': 0.44,
                'precipIntensity': 0,
                'precipIntensityMax': 0.0051,
                'precipIntensityMaxTime': 1552962600,
                'precipProbability': 0,
                'temperatureHigh': 31.34,
                'temperatureHighTime': 1552987800,
                'temperatureLow': 18.38,
                'temperatureLowTime': 1553041800,
                'apparentTemperatureHigh': 31.34,
                'apparentTemperatureHighTime': 1552987800,
                'apparentTemperatureLow': 18.38,
                'apparentTemperatureLowTime': 1553041800,
                'dewPoint': 6.99,
                'humidity': 0.36,
                'pressure': 1009.6,
                'windSpeed': 1.81,
                'windGust': 6.03,
                'windGustTime': 1552987800,
                'windBearing': 325,
                'cloudCover': 0.18,
                'uvIndex': 9,
                'uvIndexTime': 1552977000,
                'visibility': 16.09,
                'ozone': 283.35,
                'temperatureMin': 16.92,
                'temperatureMinTime': 1552951800,
                'temperatureMax': 31.34,
                'temperatureMaxTime': 1552987800,
                'apparentTemperatureMin': 16.92,
                'apparentTemperatureMinTime': 1552951800,
                'apparentTemperatureMax': 31.34,
                'apparentTemperatureMaxTime': 1552987800
            },
            {
                'time': 1553020200,
                'summary': 'Clear throughout the day.',
                'icon': 'clear-day',
                'sunriseTime': 1553043420,
                'sunsetTime': 1553087009,
                'moonPhase': 0.47,
                'precipIntensity': 0,
                'precipIntensityMax': 0.0051,
                'precipIntensityMaxTime': 1553103000,
                'precipProbability': 0,
                'temperatureHigh': 32.16,
                'temperatureHighTime': 1553070600,
                'temperatureLow': 17.63,
                'temperatureLowTime': 1553124600,
                'apparentTemperatureHigh': 32.16,
                'apparentTemperatureHighTime': 1553070600,
                'apparentTemperatureLow': 17.63,
                'apparentTemperatureLowTime': 1553124600,
                'dewPoint': 6.7,
                'humidity': 0.34,
                'pressure': 1008.38,
                'windSpeed': 0.93,
                'windGust': 6.46,
                'windGustTime': 1553070600,
                'windBearing': 115,
                'cloudCover': 0.03,
                'uvIndex': 9,
                'uvIndexTime': 1553063400,
                'visibility': 16.09,
                'ozone': 290.86,
                'temperatureMin': 18.38,
                'temperatureMinTime': 1553041800,
                'temperatureMax': 32.16,
                'temperatureMaxTime': 1553070600,
                'apparentTemperatureMin': 18.38,
                'apparentTemperatureMinTime': 1553041800,
                'apparentTemperatureMax': 32.16,
                'apparentTemperatureMaxTime': 1553070600
            },
            {
                'time': 1553106600,
                'summary': 'Clear throughout the day.',
                'icon': 'clear-day',
                'sunriseTime': 1553129749,
                'sunsetTime': 1553173442,
                'moonPhase': 0.52,
                'precipIntensity': 0.0025,
                'precipIntensityMax': 0.0076,
                'precipIntensityMaxTime': 1553106600,
                'precipProbability': 0.04,
                'precipType': 'rain',
                'temperatureHigh': 32.64,
                'temperatureHighTime': 1553160600,
                'temperatureLow': 18.87,
                'temperatureLowTime': 1553211000,
                'apparentTemperatureHigh': 32.64,
                'apparentTemperatureHighTime': 1553160600,
                'apparentTemperatureLow': 18.87,
                'apparentTemperatureLowTime': 1553211000,
                'dewPoint': 6.53,
                'humidity': 0.33,
                'pressure': 1010.05,
                'windSpeed': 1.32,
                'windGust': 5.94,
                'windGustTime': 1553189400,
                'windBearing': 27,
                'cloudCover': 0,
                'uvIndex': 10,
                'uvIndexTime': 1553149800,
                'visibility': 16.09,
                'ozone': 277.11,
                'temperatureMin': 17.63,
                'temperatureMinTime': 1553124600,
                'temperatureMax': 32.64,
                'temperatureMaxTime': 1553160600,
                'apparentTemperatureMin': 17.63,
                'apparentTemperatureMinTime': 1553124600,
                'apparentTemperatureMax': 32.64,
                'apparentTemperatureMaxTime': 1553160600
            },
            {
                'time': 1553193000,
                'summary': 'Clear throughout the day.',
                'icon': 'clear-day',
                'sunriseTime': 1553216079,
                'sunsetTime': 1553259875,
                'moonPhase': 0.55,
                'precipIntensity': 0,
                'precipIntensityMax': 0.0025,
                'precipIntensityMaxTime': 1553193000,
                'precipProbability': 0,
                'temperatureHigh': 31.27,
                'temperatureHighTime': 1553247000,
                'temperatureLow': 18.39,
                'temperatureLowTime': 1553301000,
                'apparentTemperatureHigh': 31.27,
                'apparentTemperatureHighTime': 1553247000,
                'apparentTemperatureLow': 18.39,
                'apparentTemperatureLowTime': 1553301000,
                'dewPoint': 4.76,
                'humidity': 0.29,
                'pressure': 1012.2,
                'windSpeed': 3.23,
                'windGust': 5.94,
                'windGustTime': 1553193000,
                'windBearing': 328,
                'cloudCover': 0,
                'uvIndex': 10,
                'uvIndexTime': 1553236200,
                'visibility': 16.09,
                'ozone': 275.86,
                'temperatureMin': 18.87,
                'temperatureMinTime': 1553211000,
                'temperatureMax': 31.27,
                'temperatureMaxTime': 1553247000,
                'apparentTemperatureMin': 18.87,
                'apparentTemperatureMinTime': 1553211000,
                'apparentTemperatureMax': 31.27,
                'apparentTemperatureMaxTime': 1553247000
            },
            {
                'time': 1553279400,
                'summary': 'Partly cloudy starting in the evening.',
                'icon': 'partly-cloudy-night',
                'sunriseTime': 1553302408,
                'sunsetTime': 1553346308,
                'moonPhase': 0.58,
                'precipIntensity': 0,
                'precipIntensityMax': 0.0025,
                'precipIntensityMaxTime': 1553293800,
                'precipProbability': 0,
                'temperatureHigh': 31.27,
                'temperatureHighTime': 1553333400,
                'temperatureLow': 18.94,
                'temperatureLowTime': 1553383800,
                'apparentTemperatureHigh': 31.27,
                'apparentTemperatureHighTime': 1553333400,
                'apparentTemperatureLow': 18.94,
                'apparentTemperatureLowTime': 1553383800,
                'dewPoint': 5.21,
                'humidity': 0.31,
                'pressure': 1012.02,
                'windSpeed': 4.65,
                'windGust': 9.09,
                'windGustTime': 1553337000,
                'windBearing': 316,
                'cloudCover': 0.14,
                'uvIndex': 10,
                'uvIndexTime': 1553322600,
                'visibility': 16.09,
                'ozone': 277.38,
                'temperatureMin': 18.39,
                'temperatureMinTime': 1553301000,
                'temperatureMax': 31.27,
                'temperatureMaxTime': 1553333400,
                'apparentTemperatureMin': 18.39,
                'apparentTemperatureMinTime': 1553301000,
                'apparentTemperatureMax': 31.27,
                'apparentTemperatureMaxTime': 1553333400
            },
            {
                'time': 1553365800,
                'summary': 'Mostly cloudy until evening.',
                'icon': 'partly-cloudy-day',
                'sunriseTime': 1553388737,
                'sunsetTime': 1553432741,
                'moonPhase': 0.62,
                'precipIntensity': 0.0025,
                'precipIntensityMax': 0.0127,
                'precipIntensityMaxTime': 1553445000,
                'precipProbability': 0.06,
                'precipType': 'rain',
                'temperatureHigh': 30.91,
                'temperatureHighTime': 1553427000,
                'temperatureLow': 18.51,
                'temperatureLowTime': 1553470200,
                'apparentTemperatureHigh': 30.91,
                'apparentTemperatureHighTime': 1553427000,
                'apparentTemperatureLow': 18.51,
                'apparentTemperatureLowTime': 1553470200,
                'dewPoint': 6.63,
                'humidity': 0.33,
                'pressure': 1010.38,
                'windSpeed': 4.26,
                'windGust': 10.18,
                'windGustTime': 1553416200,
                'windBearing': 315,
                'cloudCover': 0.54,
                'uvIndex': 5,
                'uvIndexTime': 1553405400,
                'visibility': 16.09,
                'ozone': 278.5,
                'temperatureMin': 18.94,
                'temperatureMinTime': 1553383800,
                'temperatureMax': 30.91,
                'temperatureMaxTime': 1553427000,
                'apparentTemperatureMin': 18.94,
                'apparentTemperatureMinTime': 1553383800,
                'apparentTemperatureMax': 30.91,
                'apparentTemperatureMaxTime': 1553427000
            }
        ]
    },
    'flags': {
        'sources': [
            'cmc',
            'gfs',
            'icon',
            'isd',
            'madis'
        ],
        'nearest-station': 10.85,
        'units': 'si'
    },
    'offset': 5.5
};
